/* ac_ffi.h — C ABI over ac-core for the macOS SwiftUI app.
   Generated by cbindgen from ffi/src/lib.rs. Do not edit by hand. */

#ifndef AC_FFI_H
#define AC_FFI_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// The ac-core semver the app was linked against. Points at static memory — do
// NOT pass this one to `ac_string_free`.
const char *ac_core_version(void);

// The server directory as a JSON array. Live from treestats when reachable,
// otherwise the compiled-in snapshot — this never fails, so it never returns
// null. Free with `ac_string_free`.
char *ac_servers_json(void);

// The persisted config (prefix, saved servers, last selection) as JSON. Free
// with `ac_string_free`.
char *ac_config_get(void);

// Replace the persisted config from a JSON object. Returns null on success, or
// an error string (free it with `ac_string_free`).
//
// # Safety
// `json` must be null or a valid NUL-terminated C string.
char *ac_config_set(const char *json);

// Whether the game is set up, as JSON `{"ready":bool,"ac_dir":string|null,
// "error":string|null}`. `ready:false` with an `error` explaining what is
// missing is the signal for the app to show the setup screen. Free with
// `ac_string_free`.
char *ac_detect(void);

// Start first-run setup on a background thread. Calling it while setup is
// already running does nothing; calling it after a run *finished* starts a fresh
// one, which is what "Try again" needs — the steps are idempotent, so a retry
// skips everything that already succeeded and resumes at the one that broke.
// Poll `ac_setup_poll` for progress.
void ac_setup_start(void);

// Ask a running setup to stop. Returns immediately; the run ends at the next
// cancellation point — at once during a download, otherwise when the step's
// external command (wineboot, the installer wizard) returns. Watch
// `ac_setup_poll` for `done:true` with `cancelled:true`. Steps are idempotent, so
// `ac_setup_start` afterwards resumes rather than starting over.
void ac_setup_cancel(void);

// A snapshot of the whole setup run as JSON:
//
// ```json
// {"started":bool, "done":bool, "cancelled":bool, "error":string|null,
//  "steps":[{"step":"download_client", "label":"Downloading the game client",
//            "detail":"The original retail installer, about 570 MB",
//            "state":"pending|running|done|skipped|failed",
//            "fraction":0.0..1.0, "message":"312 MB of 571 MB · 8.4 MB/s"}, …]}
// ```
//
// Every step is present from the first call, so polling *before*
// `ac_setup_start` returns the plan (all `pending`) and the app can show the
// list before the user commits to it. When `done` is true setup has finished —
// successfully if `error` is null, otherwise `error` says why it stopped and the
// step that broke is the one in state `failed`. Free with `ac_string_free`.
char *ac_setup_poll(void);

// Launch the client for a server (a JSON `Server` object) and account. Returns
// null on a successful spawn, or an error string (free it with
// `ac_string_free`). The game runs detached; this returns as soon as it starts.
//
// # Safety
// All three pointers must be null or valid NUL-terminated C strings.
char *ac_launch(const char *server_json, const char *account, const char *password);

// Free a string returned by any of the `*_json` / `*_get` / `ac_detect` /
// `ac_setup_poll` / `ac_config_set` / `ac_launch` calls. Null is ignored. Never
// call this on `ac_core_version`'s result.
//
// # Safety
// `p` must be null or a pointer previously returned by one of this library's
// string-returning functions, and must not be used afterwards.
void ac_string_free(char *p);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* AC_FFI_H */
