/* ac_ffi.h — C ABI over ac-core for the macOS SwiftUI app.
   Generated by cbindgen from ffi/src/lib.rs. Do not edit by hand. */

#ifndef AC_FFI_H
#define AC_FFI_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// The ac-core semver the app was linked against. Points at static memory — do
// NOT pass this one to `ac_string_free`.
const char *ac_core_version(void);

// The server directory as a JSON array. Live from treestats when reachable,
// otherwise the compiled-in snapshot — this never fails, so it never returns
// null. Free with `ac_string_free`.
char *ac_servers_json(void);

// The persisted config (prefix, saved servers, last selection) as JSON. Free
// with `ac_string_free`.
char *ac_config_get(void);

// Replace the persisted config from a JSON object. Returns null on success, or
// an error string (free it with `ac_string_free`).
//
// # Safety
// `json` must be null or a valid NUL-terminated C string.
char *ac_config_set(const char *json);

// Whether the game is set up, as JSON `{"ready":bool,"ac_dir":string|null,
// "error":string|null}`. `ready:false` with an `error` explaining what is
// missing is the signal for the app to show the setup screen. Free with
// `ac_string_free`.
char *ac_detect(void);

// Start first-run setup on a background thread. Calling it while setup is
// already running does nothing; calling it after a run *finished* starts a fresh
// one, which is what "Try again" needs — the steps are idempotent, so a retry
// skips everything that already succeeded and resumes at the one that broke.
// Poll `ac_setup_poll` for progress.
void ac_setup_start(void);

// Ask a running setup to stop. Returns immediately; the run ends at the next
// cancellation point — at once during a download, otherwise when the step's
// external command (wineboot, the installer wizard) returns. Watch
// `ac_setup_poll` for `done:true` with `cancelled:true`. Steps are idempotent, so
// `ac_setup_start` afterwards resumes rather than starting over.
void ac_setup_cancel(void);

// A snapshot of the whole setup run as JSON:
//
// ```json
// {"started":bool, "done":bool, "cancelled":bool, "error":string|null,
//  "steps":[{"step":"download_client", "label":"Downloading the game client",
//            "detail":"The original retail installer, about 570 MB",
//            "state":"pending|running|done|skipped|failed",
//            "fraction":0.0..1.0, "message":"312 MB of 571 MB · 8.4 MB/s"}, …]}
// ```
//
// Every step is present from the first call, so polling *before*
// `ac_setup_start` returns the plan (all `pending`) and the app can show the
// list before the user commits to it. When `done` is true setup has finished —
// successfully if `error` is null, otherwise `error` says why it stopped and the
// step that broke is the one in state `failed`. Free with `ac_string_free`.
char *ac_setup_poll(void);

// Launch the client for a server (a JSON `Server` object) and account. Returns
// null on a successful spawn, or an error string (free it with
// `ac_string_free`). The game runs detached; this returns as soon as it starts.
//
// # Safety
// All three pointers must be null or valid NUL-terminated C strings.
char *ac_launch(const char *server_json, const char *account, const char *password);

// What a reset would delete, as a JSON array of `{"label", "path"}`.
//
// The UI lists these before asking the user to confirm, so the warning names the
// actual directories on this machine rather than a hardcoded description that
// could drift from what `ac_reset` really removes.
char *ac_reset_targets_json(void);

// Delete the install: prefix, engine, and settings. Returns null on success, or
// an error string. After this, `ac_detect` reports not-ready and the frontend
// routes back to setup.
//
// Refused while a setup run is in flight — deleting the prefix out from under
// the thread building it would leave a mess neither side could describe.
//
// A *running* prefix is different: that one we end ourselves first. Decal's agent
// is left alive on purpose once opened (see [`ac_decal_open_settings`]), and
// deleting the prefix from under a live wineserver strands its menu-bar icon with
// nothing left on disk to explain it.
char *ac_reset(void);

// Is Decal provisioned in the prefix? `"1"` or `"0"`, so the UI can tell "off"
// from "on but not installed yet" and prompt to re-run setup.
char *ac_decal_installed(void);

// The registered plugins, as a JSON array of `{"clsid","name","enabled"}`.
// Empty when Decal is not installed — not an error, just nothing to show.
char *ac_decal_plugins_json(void);

// Turn one plugin on or off. Null on success, else an error string.
//
// # Safety
// `clsid` must be a valid NUL-terminated C string.
char *ac_decal_set_plugin(const char *clsid, bool enabled);

// Register a plugin from a DLL on disk, disabled. Returns null on success, else
// an error string.
//
// # Safety
// `path` must be a valid NUL-terminated C string.
char *ac_decal_add_plugin(const char *path);

// Open Decal's own configuration UI (`DenAgent.exe`). Null on success, else an
// error string.
//
// The agent has **no window**: it puts an icon in the menu bar and shows its
// dialog when that is clicked. So this returns as soon as the process is spawned,
// and the UI has to say where to look. It also stakes out no opinion about an
// agent that is already running — Decal's own single-instance handling does, and
// a second launch just surfaces the first.
char *ac_decal_open_settings(void);

// Install a Decal plugin from a `.zip`, `.msi` or `.exe` on the host filesystem.
// Null on success, else an error string.
//
// A zip is the best thing to pass: it is unpacked into the prefix whole and the
// installer inside is run, so nothing has to be guessed about which neighbouring
// files that installer needs.
//
// **Blocks until the installer is done**, which includes however long the user
// spends in its dialogs — the package gets its own UI, since a third-party
// installer may have questions only the user can answer. Call it off the UI
// thread.
//
// # Safety
// `path` must be a valid NUL-terminated C string.
char *ac_decal_install_plugin(const char *path);

// Shut down everything still running in the prefix. Call when the app quits.
//
// End the Wine session at quit, if this run of the app left anything in it.
//
// Decal's agent outlives the settings sheet by design, and its status icon is
// owned by the prefix's `explorer.exe`, not by the agent — so leaving the session
// up leaks an icon nothing else will clear. Silent: at quit there is nobody left
// to report a failure to, and the usual case is nothing to kill.
//
// Killing the session ends the **game** too, so this is a no-op unless the agent
// was actually started — see `ac_core::runtime::shutdown_on_quit`. It used to be
// unconditional, which meant quitting the launcher mid-session killed the game.
void ac_decal_shutdown(void);

// Free a string returned by any of the `*_json` / `*_get` / `ac_detect` /
// `ac_setup_poll` / `ac_config_set` / `ac_launch` calls. Null is ignored. Never
// call this on `ac_core_version`'s result.
//
// # Safety
// `p` must be null or a pointer previously returned by one of this library's
// string-returning functions, and must not be used afterwards.
void ac_string_free(char *p);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* AC_FFI_H */
